version: "2"

services:
  com.sixt.service.test-service:
    build:
      context: ../../../build/docker
      dockerfile: Dockerfile
    environment:
      - "kafkaServer=kafka:9092"
      - "logLevel=DEBUG"
      - "registry=consul"
      - "servicePort=42000"
    entrypoint: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -server -Dfile.encoding=UTF8 -XX:-OmitStackTraceInFastThrow -Djava.security.egd=file:/dev/./urandom -jar /app.jar -registryServer consul:8500
    ports:
      - "5005"
      - "42000"
    depends_on:
      - zookeeper
      - consul
      - kafka

  consul:
    image: consul:0.7.5
    command: "agent -server -bootstrap -data-dir=/tmp -client=0.0.0.0 -ui"
    ports:
      - "8500"
    hostname: consul

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181"
    hostname: zookeeper

  kafka:
    image: wurstmeister/kafka:0.10.1.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "inbox_test:3:1,inbox-com.sixt.service.test-service:3:1,events:1:1" # events should be last
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Disable topic auto creation -> otherwise we have an occasional concurrency bug in the tests
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/start_kafka.sh:/tmp/start_kafka.sh
    depends_on:
      - "zookeeper"
    entrypoint: /tmp/start_kafka.sh
    hostname: kafka